### ISSUE TITLE
Save hypothesis database in GitHub Actions cache

### ISSUE THREAD

**Issue by chanhosuh** [curveresearch/curvesim#175]
This will let us more thoroughly test new cases and ensure we have fixed breaking cases.

```
    - name: Cache Hypothesis database
      uses: actions/cache@v2
      id: cache-hypothesis
      with:
        path: .hypothesis
        key: ${{ runner.os }}-hypothesis-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-hypothesis-
```
