### ISSUE TITLE
Use tox to run test matrix

### ISSUE THREAD

**Issue by chanhosuh** [curveresearch/curvesim#93]
Should run against mac and windows OSes too, and explicitly run against supported python versions, e.g.

```
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
```

Resources:
- https://github.com/nedbat/scriv/blob/main/.github/workflows/tests.yml
- https://github.com/nedbat/scriv/blob/main/tox.ini
